fix: correct Nix package name from nodejs-20_x to nodejs_20
- Fix undefined variable error in Nixpacks
- Nix package name is 'nodejs_20' not 'nodejs-20_x'
- Use underscore instead of hyphen, no _x suffix

Error was:
error: undefined variable 'nodejs-20_x'
at /app/.nixpacks/nixpkgs-ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7.nix:19:9